"""empty message

Revision ID: 29704c696cf9
Revises: 59a727ac9f0c
Create Date: 2022-11-03 05:48:37.684246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29704c696cf9'
down_revision = '59a727ac9f0c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
