"""empty message

Revision ID: 1232ebfbea97
Revises: 6a393c8b05ee
Create Date: 2022-11-03 07:43:22.382541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1232ebfbea97'
down_revision = '6a393c8b05ee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
